---

custom:
- https://www.comebackalive.in.ua/donate
- https://github.com/vshymanskyy/StandWithUkraine#for-maintainers-and-authors
- https://www.paypal.me/webknjazCZ
- https://webknjaz.me

github:
- webknjaz

ko_fi: webknjaz

liberapay: webknjaz

open_collective: webknjaz

# patreon: webknjaz  # not in use because of the ties with ruscism

thanks_dev: u/gh/webknjaz

...
