---

ci:
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.37.1
  hooks:
  - id: yamllint
    args:
    - --strict

- repo: https://github.com/rhysd/actionlint.git
  rev: v1.7.7
  hooks:
  - id: actionlint

...
